// Documentation review: queries the last 5 merged cycle goals from the DB,
// spawns the documentation agent with those goals as context, and instructs it to:
//   (1) update the 'Current capabilities' section of README.md
//   (2) write/overwrite sidecar/data/POLICIES.md summarising governance rules in force.
// Returns { policiesPath, readmeUpdated, summary }.
import path from 'node:path';
import fs from 'node:fs';
import { paths, BUDGETS } from './config.js';
import { spawnWorker } from './worker.js';
import { ROLES } from './roles.js';

export async function runDocumentationReview(db, { _worker = spawnWorker } = {}) {
  // Goals with status='advanced' were merged AND auditor-aligned (see loop.js line 186).
  const goalRows = db.prepare(
    "SELECT text FROM goal WHERE status = 'advanced' ORDER BY created_ts DESC LIMIT 5"
  ).all();
  const goals = goalRows.map((r) => r.text).filter(Boolean);

  const policiesPath = path.join(paths.data, 'POLICIES.md');
  fs.mkdirSync(paths.data, { recursive: true });

  const readmePath = path.join(paths.root, 'README.md');
  const readmeBefore = fs.existsSync(readmePath) ? fs.statSync(readmePath).mtimeMs : 0;

  const goalsList = goals.length > 0
    ? goals.map((g, i) => `${i + 1}. ${g}`).join('\n')
    : '(no merged cycles recorded yet)';

  const role = ROLES.documentation;
  const prompt =
    'Here are the last ' + goals.length + ' goals that completed and merged through the council gate:\n\n' +
    goalsList + '\n\n' +
    'Your tasks:\n' +
    '1. Open README.md at the repository root (' + readmePath + '). ' +
    "Find or create a '## Current capabilities' section (place it after the '## Features' section if creating). " +
    'Update it to list the concrete capabilities this harness currently demonstrates, informed by the merged goals above ' +
    'and your reading of the codebase. Be specific and accurate — do not list capabilities that do not exist in the code.\n' +
    '2. Write (or overwrite) this file: ' + policiesPath + '\n' +
    '   Write a POLICIES.md document summarising all governance rules currently in force: ' +
    'the merge gate conditions (testPass && aligned && clean), budget caps (usdPerRun, usdPerCycle, usdPerDay), ' +
    'separation-of-duties rules, per-role tool restrictions, Layer-B hook enforcement (policy-hook.mjs), ' +
    'and policy rules from sidecar/src/policy.js and sidecar/src/governance.js. ' +
    'Use clear headings and machine-readable phrasing. This file MUST be written — it is your primary deliverable.\n' +
    'End your message with a one-sentence summary of what you changed.';

  const res = await _worker({
    cwd: paths.root,
    prompt,
    charter: role.charter,
    model: role.model,
    allowedTools: role.tools,
    maxBudgetUsd: role.maxBudgetUsd ?? BUDGETS.usdPerRun,
  });

  const readmeAfter = fs.existsSync(readmePath) ? fs.statSync(readmePath).mtimeMs : 0;
  const readmeUpdated = readmeAfter > readmeBefore;

  // Fallback: if the agent did not write POLICIES.md, write a stub so the path is always valid.
  if (!fs.existsSync(policiesPath)) {
    fs.writeFileSync(
      policiesPath,
      '# Governance Policies\n\n' +
        '_Generated by documentation review — no merged cycles found yet._\n\n' +
        '## Merge gate\n\n' +
        'A change merges only when `testPass && aligned && clean` are all true.\n\n' +
        '## Budget caps\n\n' +
        'See `sidecar/src/config.js` BUDGETS: `usdPerRun`, `usdPerCycle`, `usdPerDay`, `workerTimeoutMs`.\n\n' +
        '## Separation of duties\n\n' +
        'An approver may never be the author or downstream of the author (enforced by policy.js).\n\n' +
        '## Per-role tool restrictions\n\n' +
        'See `sidecar/src/roles.js` for each role\'s `tools` array. Workers may only call listed tools.\n\n' +
        '## Layer-B hook enforcement\n\n' +
        '`sidecar/hooks/policy-hook.mjs` blocks dangerous git commands (merge, push, rebase, reset) inside worker shells.\n',
      'utf8'
    );
  }

  const resultText = res.result?.result ?? '';
  const lines = resultText.trim().split(/\n+/).filter((l) => l.trim());
  const summary = (lines.at(-1) ?? 'Documentation review complete.').slice(0, 200);

  return { policiesPath, readmeUpdated, summary };
}
